server:
  port: 8800
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useSSL=true&serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml